# Generated by Django 5.1.4 on 2024-12-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ser',
            new_name='user',
        ),
    ]
